function plural(count: number, suffix = "s") {
  return count === 1 ? "" : suffix;
}

function filteredOrAll(isFiltered: boolean) {
  return isFiltered ? "filtrados" : "todos";
}

export const Labels = {
  appTitle: "Vidriera",
  appDescription: "Catálogo y stock de Vidriera",
  logoAlt: "Vidriera",

  emailFieldLabel: "Email",
  passwordFieldLabel: "Contraseña",
  loginSubmitting: "Ingresando...",
  loginSubmit: "Ingresar",

  loadingProducts: "Cargando productos...",
  noProductsOrSectionsYet: "Todavía no hay productos ni carátulas cargadas.",
  noSearchMatches: "Ningún producto coincide con la búsqueda.",

  productSheetFormLabel: "Alta de Fichas",
  chooseFilesPlural: "Elegir archivos",
  sectionCreateFormTitle: "Alta de Carátulas",
  sectionCoverOptionalHint: (maxLabel: string) => `PDF opcional, máx. ${maxLabel}`,
  chooseFileSingular: "Elegir archivo",
  newProductSubmitTitle: "Nuevo producto",
  newSectionSubmitTitle: "Nueva carátula",
  uploadProductsSubmitTitle: (count: number) => `Cargar ${count} productos`,
  uploadSectionsSubmitTitle: (count: number) => `Cargar ${count} carátulas`,
  renameFilesButton: "Renombrar archivos",
  renameFilesButtonEdited: (count: number) => `Nombres editados (${count})`,
  renameFilesTitle: "Renombrar archivos antes de subir",
  renameFilesHint: "Estos nombres se van a usar en vez del nombre del archivo.",
  renameFilesApply: "Aplicar nombres",
  renameFilesFileColumnLabel: "Archivo",
  renameFilesNameColumnLabel: "Nombre",
  createNamedSectionsButton: "Alta masiva sin PDF",
  createNamedSectionsTitle: "Crear varias carátulas",
  createNamedSectionsHint: "Se crean solo con nombre, sin PDF — se les puede asociar productos como a cualquier carátula.",
  addAnotherNameButton: "+ Agregar otra",
  removeNameRowTitle: "Quitar",
  createNamedSectionsSubmit: (count: number) => `Crear (${count})`,

  searchPlaceholder: "Buscar por nombre...",
  stockFilterAllLabel: "Todos",
  stockFilterVisibleLabel: "Visualizados",
  stockFilterHiddenLabel: "No visualizados",
  markAll: (isFiltered: boolean) => `Marcar ${filteredOrAll(isFiltered)}`,
  unmarkAll: (isFiltered: boolean) => `Desmarcar ${filteredOrAll(isFiltered)}`,
  deleteSelectedCount: (count: number) => `Borrar seleccionados (${count})`,
  deleteAllOrFiltered: (isFiltered: boolean) => `Borrar ${filteredOrAll(isFiltered)}`,
  cancelBulkAssignMode: "Cancelar selección",
  startBulkAssignMode: "Seleccionar productos",

  bulkAssignHint: (count: number) => `Tildá los productos de la lista para asociarlos a una carátula o borrarlos (${count} seleccionado${plural(count)}).`,
  noSectionOption: "Sin carátula",
  applying: "Aplicando...",
  apply: (count: number) => `Aplicar (${count})`,

  confirmBulkDeleteQuestion: (label: string) => `¿Borrar ${label}? Esta acción no se puede deshacer.`,
  bulkDeleting: "Borrando...",
  confirmYesDelete: "Sí, borrar",
  cancel: "Cancelar",

  generatingCatalog: "Actualizando catálogo...",
  generateCatalogButton: (count: number) => `Actualizar catálogo (${count} con stock y ficha)`,
  catalogGenerationHint: "Puede tardar un momento si el catálogo tiene muchos productos.",
  preparingFilesProgress: (current: number, total: number) => `Preparando archivos (${current}/${total})`,
  generatingImagesProgress: (current: number, total: number) => `Generando imágenes (${current}/${total})`,
  linkPrefix: "Link fijo:",

  dragToReorder: "Arrastrar para reordenar",
  positionInOrder: "Posición en el orden",
  productNameFieldTitle: "Nombre",
  priceFieldTitle: "Precio",
  showPricesLabel: "Mostrar precios en este catálogo",
  optionalPricePlaceholder: "Precio",
  sectionSelectTitle: "Carátula",
  sectionParentSelectTitle: "Carátula padre",
  noParentSectionOption: "Sin carátula padre",
  confirmDeleteProductQuestion: "¿Borrar?",
  confirmDeleteSectionQuestion: "¿Borrar carátula?",
  yes: "Sí",
  sheetLoaded: "Ficha cargada",
  uploadSheet: "Subir ficha",
  delete: "Borrar",
  deleteSection: "Borrar carátula",
  collapseSection: "Colapsar carátula",
  expandSection: "Expandir carátula",
  selectForBulkAssignTitle: "Seleccionar para asociar a carátula",
  hasStockTitle: "Tiene stock",
  selectAllSectionMembersTitle: "Seleccionar todos los productos de esta carátula",
  toggleSectionStockTitle: "Marcar/desmarcar stock de todos los productos de esta carátula",

  bannerAlt: (companyName: string) => `Banner de ${companyName}`,
  uploadingBanner: "Subiendo...",
  changeBanner: "Cambiar banner",
  uploadBanner: "Subir banner",
  logout: "Salir",

  noFileChosen: "Ningún archivo elegido",
  filesChosenCount: (count: number) => `${count} archivos elegidos`,
  maxSizeSuffix: (maxLabel: string) => `(máx. ${maxLabel})`,
  optionalNamePlaceholder: "Nombre",
  optionalCodePlaceholder: "Código (opcional)",
  renameFilesCodeColumnLabel: "Código",
  fileNameConventionHint: '— nombrá el archivo "código-producto.pdf" para autocompletar',

  selectedProductsLabel: (count: number) => `${count} producto${plural(count)} seleccionado${plural(count)}`,
  filteredProductsLabel: (count: number) => `${count} producto${plural(count)} filtrado${plural(count)}`,
  allProductsLabel: (count: number) => `TODOS los productos (${count})`,

  productsNavLabel: "Productos",
  ordersNavLabel: "Pedidos",
  importPricesNavLabel: "Precios",
  importPricesTitle: "Importar precios",
  importPricesHint: "Excel con Código en la primera columna y Precio en la segunda. La primera fila se ignora (encabezado).",
  chooseExcelFile: "Elegir Excel",
  downloadTemplateButton: "Descargar plantilla",
  importingPrices: "Importando...",
  importPricesUpdatedCount: (count: number) => `${count} precio${plural(count)} actualizado${plural(count)}.`,
  importPricesNotFoundCodes: (codes: string[]) => `Códigos no encontrados: ${codes.join(", ")}`,

  loadingOrders: "Cargando pedidos...",
  noOrdersYet: "Todavía no se recibieron pedidos.",
  orderItemsCount: (count: number) => `${count} producto${plural(count)}`,
  viewOrderDetail: "Ver detalle",
  hideOrderDetail: "Ocultar detalle",
  orderBusinessNameLabel: "Razón Social",
  orderStoreNameLabel: "Nombre del local",
  orderCuitLabel: "CUIT",
  orderVatConditionLabel: "Condición frente al IVA",
  orderPhoneLabel: "Teléfono",
  orderCityLabel: "Ciudad",
  orderProvinceLabel: "Provincia",
  orderCarrierLabel: "Expreso",
  orderDeliveryAddressLabel: "Dirección de entrega",
  orderProductColumn: "Producto",
  orderCodeColumn: "Código",
  orderQuantityColumn: "Cantidad",
  notProvided: "—",
} as const;
