function plural(count: number, suffix = "s") {
  return count === 1 ? "" : suffix;
}

function filteredOrAll(isFiltered: boolean) {
  return isFiltered ? "filtrados" : "todos";
}

const planNames: Record<string, string> = { Basic: "Básico", Premium: "Premium" };

export const Labels = {
  appTitle: "Vidriera",
  appDescription: "Catálogo y stock de Vidriera",
  logoAlt: "Vidriera",

  emailFieldLabel: "Email",
  passwordFieldLabel: "Contraseña",
  loginSubmitting: "Ingresando...",
  loginSubmit: "Ingresar",
  forgotPasswordLink: "¿Olvidaste tu contraseña?",

  forgotPasswordTitle: "Recuperar contraseña",
  forgotPasswordHint: "Ingresá tu email y, si está registrado, te vamos a mandar un link para elegir una contraseña nueva.",
  forgotPasswordSubmitting: "Enviando...",
  forgotPasswordSubmit: "Enviar link",
  forgotPasswordSent: "Si el email está registrado, te llegó un mail con el link para restablecer tu contraseña.",
  backToLoginLink: "Volver a ingresar",

  resetPasswordTitle: "Elegir contraseña nueva",
  newPasswordFieldLabel: "Contraseña nueva",
  confirmPasswordFieldLabel: "Confirmar contraseña",
  resetPasswordSubmitting: "Guardando...",
  resetPasswordSubmit: "Guardar contraseña",
  resetPasswordSuccess: "Contraseña actualizada. Ya podés ingresar con la nueva.",

  loadingItems: "Cargando items...",
  noItemsOrSectionsYet: "Todavía no hay items ni carátulas cargadas.",
  noSearchMatches: "Ningún item coincide con la búsqueda.",

  itemSheetFormLabel: "Alta de Fichas",
  chooseFilesPlural: "Elegir archivos",
  sectionCreateFormTitle: "Alta de Carátulas",
  sectionCoverOptionalHint: (maxLabel: string) => `PDF opcional, máx. ${maxLabel}`,
  chooseFileSingular: "Elegir archivo",
  newItemSubmitTitle: "Nuevo item",
  newSectionSubmitTitle: "Nueva carátula",
  uploadItemsSubmitTitle: (count: number) => `Cargar ${count} items`,
  uploadSectionsSubmitTitle: (count: number) => `Cargar ${count} carátulas`,
  renameFilesButton: "Renombrar archivos",
  renameFilesButtonEdited: (count: number) => `Nombres editados (${count})`,
  renameFilesTitle: "Renombrar archivos antes de subir",
  renameFilesHint: "Estos nombres se van a usar en vez del nombre del archivo.",
  renameFilesApply: "Aplicar nombres",
  renameFilesFileColumnLabel: "Archivo",
  renameFilesNameColumnLabel: "Nombre",
  createNamedSectionsButton: "Alta masiva sin PDF",
  createNamedSectionsTitle: "Crear varias carátulas",
  createNamedSectionsHint: "Se crean solo con nombre, sin PDF — se les puede asociar items como a cualquier carátula.",
  addAnotherNameButton: "+ Agregar otra",
  removeNameRowTitle: "Quitar",
  createNamedSectionsSubmit: (count: number) => `Crear (${count})`,

  searchPlaceholder: "Buscar por nombre...",
  stockFilterAllLabel: "Todos",
  stockFilterVisibleLabel: "Visualizados",
  stockFilterHiddenLabel: "No visualizados",
  markAll: (isFiltered: boolean) => `Marcar ${filteredOrAll(isFiltered)}`,
  unmarkAll: (isFiltered: boolean) => `Desmarcar ${filteredOrAll(isFiltered)}`,
  deleteSelectedCount: (count: number) => `Borrar seleccionados (${count})`,
  deleteAllOrFiltered: (isFiltered: boolean) => `Borrar ${filteredOrAll(isFiltered)}`,
  cancelBulkAssignMode: "Cancelar selección",
  startBulkAssignMode: "Seleccionar items",

  bulkAssignHint: (count: number) => `Tildá los items de la lista para asociarlos a una carátula o borrarlos (${count} seleccionado${plural(count)}).`,
  noSectionOption: "Sin carátula",
  applying: "Aplicando...",
  apply: (count: number) => `Aplicar (${count})`,

  confirmBulkDeleteQuestion: (label: string) => `¿Borrar ${label}? Esta acción no se puede deshacer.`,
  bulkDeleting: "Borrando...",
  confirmYesDelete: "Sí, borrar",
  cancel: "Cancelar",

  generatingCatalog: "Actualizando catálogo...",
  generateCatalogButton: (count: number) => `Actualizar catálogo (${count} con stock y ficha)`,
  catalogGenerationHint: "Puede tardar un momento si el catálogo tiene muchos items.",
  preparingFilesProgress: (current: number, total: number) => `Preparando archivos (${current}/${total})`,
  generatingImagesProgress: (current: number, total: number) => `Generando imágenes (${current}/${total})`,
  linkPrefix: "Link fijo:",

  dragToReorder: "Arrastrar para reordenar",
  positionInOrder: "Posición en el orden",
  itemNameFieldTitle: "Nombre",
  priceFieldTitle: "Precio",
  showPricesLabel: "Mostrar precios en este catálogo",
  optionalPricePlaceholder: "Precio",
  sectionSelectTitle: "Carátula",
  sectionParentSelectTitle: "Carátula padre",
  noParentSectionOption: "Sin carátula padre",
  confirmDeleteItemQuestion: "¿Borrar?",
  confirmDeleteSectionQuestion: "¿Borrar carátula?",
  yes: "Sí",
  sheetLoaded: "Ficha cargada",
  uploadSheet: "Subir ficha",
  delete: "Borrar",
  deleteSection: "Borrar carátula",
  collapseSection: "Colapsar carátula",
  expandSection: "Expandir carátula",
  selectForBulkAssignTitle: "Seleccionar para asociar a carátula",
  hasStockTitle: "Tiene stock",
  selectAllSectionMembersTitle: "Seleccionar todos los items de esta carátula",
  toggleSectionStockTitle: "Marcar/desmarcar stock de todos los items de esta carátula",

  planLabel: (plan: string) => `Plan ${planNames[plan] ?? plan}`,

  bannerAlt: (companyName: string) => `Banner de ${companyName}`,
  uploadingBanner: "Subiendo...",
  changeBanner: "Cambiar banner",
  uploadBanner: "Subir banner",
  logout: "Salir",

  noFileChosen: "Ningún archivo elegido",
  filesChosenCount: (count: number) => `${count} archivos elegidos`,
  maxSizeSuffix: (maxLabel: string) => `(máx. ${maxLabel})`,
  optionalNamePlaceholder: "Nombre",
  optionalCodePlaceholder: "Código (opcional)",
  renameFilesCodeColumnLabel: "Código",
  fileNameConventionHint: '— nombrá el archivo "código-item.pdf" para autocompletar',

  selectedItemsLabel: (count: number) => `${count} item${plural(count)} seleccionado${plural(count)}`,
  filteredItemsLabel: (count: number) => `${count} item${plural(count)} filtrado${plural(count)}`,
  allItemsLabel: (count: number) => `TODOS los items (${count})`,

  itemsNavLabel: "Items",
  ordersNavLabel: "Pedidos",
  importPricesNavLabel: "Precios",
  importPricesTitle: "Importar precios",
  importPricesHint: "Excel con Código en la primera columna y Precio en la segunda. La primera fila se ignora (encabezado).",
  chooseExcelFile: "Elegir Excel",
  downloadTemplateButton: "Descargar plantilla",
  importingPrices: "Importando...",
  importPricesUpdatedCount: (count: number) => `${count} precio${plural(count)} actualizado${plural(count)}.`,
  importPricesNotFoundCodes: (codes: string[]) => `Códigos no encontrados: ${codes.join(", ")}`,

  loadingOrders: "Cargando pedidos...",
  noOrdersYet: "Todavía no se recibieron pedidos.",
  orderItemsCount: (count: number) => `${count} item${plural(count)}`,
  viewOrderDetail: "Ver detalle",
  hideOrderDetail: "Ocultar detalle",
  downloadOrderExcelButton: "Descargar Excel",
  downloadingOrderExcel: "Descargando...",
  untitledOrder: "Pedido",
  orderItemColumn: "Item",
  orderCodeColumn: "Código",
  orderQuantityColumn: "Cantidad",
  notProvided: "—",

  orderFormNavLabel: "Formulario de pedido",
  loadingOrderFormFields: "Cargando formulario...",
  orderFormFieldsHint:
    "Elegí qué campos le vas a pedir a tus clientes al hacer un pedido, cuáles son obligatorios, y en qué orden aparecen.",
  noCustomOrderFormFieldsHint:
    "Todavía no personalizaste el formulario de pedido — se está usando el formulario estándar (Razón Social, CUIT, Email, Provincia, Ciudad, Dirección de entrega, Nombre del local, Condición IVA, Teléfono, Expreso).",
  addOrderFormFieldTitle: "Agregar campo",
  fieldLabelPlaceholder: "Nombre del campo",
  fieldTypeLabel: "Tipo",
  fieldRequiredLabel: "Obligatorio",
  addFieldButton: "Agregar",
  addingField: "Agregando...",
  confirmDeleteOrderFieldQuestion: "¿Borrar este campo?",
  orderFieldTypeFreeText: "Texto libre",
  orderFieldTypeName: "Nombre (sin números)",
  orderFieldTypeEmail: "Email",
  orderFieldTypeCuit: "CUIT",
  orderFieldTypeProvince: "Provincia",
  orderFieldTypeVatCondition: "Condición frente al IVA",
} as const;
